use std::fmt::Display;

use super::register::Register;

#[derive(Debug)]
pub enum Instruction {
    Unknown,
    Sll(Register, Register, u8),
    Srl(Register, Register, u8),
    Sra(Register, Register, u8),
    Sllv(Register, Register, Register),
    Srlv(Register, Register, Register),
    Srav(Register, Register, Register),
    Jr(Register),
    Jalr(Register, Register),
    Movz(Register, Register, Register),
    Movn(Register, Register, Register),
    Syscall,
    Break,
    Sync,
    Mfhi(Register),
    Mthi(Register),
    Mflo(Register),
    Mtlo(Register),
    Dsllv(Register, Register, Register),
    Dsrav(Register, Register, Register),
    Dsrlv(Register, Register, Register),
    Mult(Register, Register),
    Multu(Register, Register),
    Div(Register, Register),
    Divu(Register, Register),
    Add(Register, Register, Register),
    Addu(Register, Register, Register),
    Sub(Register, Register, Register),
    Subu(Register, Register, Register),
    And(Register, Register, Register),
    Or(Register, Register, Register),
    Xor(Register, Register, Register),
    Nor(Register, Register, Register),
    Mfsa(Register),
    Mtsa(Register),
    Slt(Register, Register, Register),
    Sltu(Register, Register, Register),
    Dadd(Register, Register, Register),
    Daddu(Register, Register, Register),
    Dsub(Register, Register, Register),
    Dsubu(Register, Register, Register),
    Tge(Register, Register),
    Tgeu(Register, Register),
    Tlt(Register, Register),
    Tltu(Register, Register),
    Teq(Register, Register),
    Tne(Register, Register),
    Dsll(Register, Register, u8),
    Dsrl(Register, Register, u8),
    Dsra(Register, Register, u8),
    Dsll32(Register, Register, u8),
    Dsrl32(Register, Register, u8),
    Dsra32(Register, Register, u8),
    Bgez(Register, u16),
    J(u32),
    Jal(u32),
    Beq(Register, Register, u16),
    Bne(Register, Register, u16),
    Addiu(Register, Register, u16),
    Andi(Register, Register, u16),
    Ori(Register, Register, u16),
    Lui(Register, u16),
    Ei,
    Sq(Register, Register, u16),
    Lh(Register, Register, u16),
    Lw(Register, Register, u16),
    Lbu(Register, Register, u16),
    Lwr(Register, Register, u16),
    Sb(Register, Register, u16),
    Sh(Register, Register, u16),
    Sw(Register, Register, u16),
    Ld(Register, Register, u16),
    Sd(Register, Register, u16),
}

impl Instruction {
    fn definitions(&self) -> impl Iterator<Item = Register> {
        (match self {
            Instruction::Unknown => [None, None],
            Instruction::Sll(a, _, _) => [Some(*a), None],
            Instruction::Srl(a, _, _) => [Some(*a), None],
            Instruction::Sra(a, _, _) => [Some(*a), None],
            Instruction::Sllv(a, _, _) => [Some(*a), None],
            Instruction::Srlv(a, _, _) => [Some(*a), None],
            Instruction::Srav(a, _, _) => [Some(*a), None],
            Instruction::Jr(_) => [None, None],
            Instruction::Jalr(a, _) => [Some(*a), None],
            Instruction::Movz(a, _, _) => [Some(*a), None],
            Instruction::Movn(a, _, _) => [Some(*a), None],
            Instruction::Syscall => [None, None],
            Instruction::Break => [None, None],
            Instruction::Sync => [None, None],
            Instruction::Mfhi(a) => [Some(*a), None],
            Instruction::Mthi(_) => [None, None],
            Instruction::Mflo(a) => [Some(*a), None],
            Instruction::Mtlo(_) => [None, None],
            Instruction::Dsllv(a, _, _) => [Some(*a), None],
            Instruction::Dsrav(a, _, _) => [Some(*a), None],
            Instruction::Dsrlv(a, _, _) => [Some(*a), None],
            Instruction::Mult(_, _) => [Some(Register::Lo), Some(Register::Hi)],
            Instruction::Multu(_, _) => [Some(Register::Lo), Some(Register::Hi)],
            Instruction::Div(_, _) => [Some(Register::Lo), Some(Register::Hi)],
            Instruction::Divu(_, _) => [Some(Register::Lo), Some(Register::Hi)],
            Instruction::Add(a, _, _) => [Some(*a), None],
            Instruction::Addu(a, _, _) => [Some(*a), None],
            Instruction::Sub(a, _, _) => [Some(*a), None],
            Instruction::Subu(a, _, _) => [Some(*a), None],
            Instruction::And(a, _, _) => [Some(*a), None],
            Instruction::Or(a, _, _) => [Some(*a), None],
            Instruction::Xor(a, _, _) => [Some(*a), None],
            Instruction::Nor(a, _, _) => [Some(*a), None],
            Instruction::Mfsa(a) => [Some(*a), None],
            Instruction::Mtsa(_) => [None, None],
            Instruction::Slt(a, _, _) => [Some(*a), None],
            Instruction::Sltu(a, _, _) => [Some(*a), None],
            Instruction::Dadd(a, _, _) => [Some(*a), None],
            Instruction::Daddu(a, _, _) => [Some(*a), None],
            Instruction::Dsub(a, _, _) => [Some(*a), None],
            Instruction::Dsubu(a, _, _) => [Some(*a), None],
            Instruction::Tge(_, _) => [None, None],
            Instruction::Tgeu(_, _) => [None, None],
            Instruction::Tlt(_, _) => [None, None],
            Instruction::Tltu(_, _) => [None, None],
            Instruction::Teq(_, _) => [None, None],
            Instruction::Tne(_, _) => [None, None],
            Instruction::Dsll(a, _, _) => [Some(*a), None],
            Instruction::Dsrl(a, _, _) => [Some(*a), None],
            Instruction::Dsra(a, _, _) => [Some(*a), None],
            Instruction::Dsll32(a, _, _) => [Some(*a), None],
            Instruction::Dsrl32(a, _, _) => [Some(*a), None],
            Instruction::Dsra32(a, _, _) => [Some(*a), None],
            Instruction::Bgez(_, _) => [None, None],
            Instruction::J(_) => [None, None],
            Instruction::Jal(_) => [Some(Register::Ra), None],
            Instruction::Beq(_, _, _) => [None, None],
            Instruction::Bne(_, _, _) => [None, None],
            Instruction::Addiu(a, _, _) => [Some(*a), None],
            Instruction::Andi(a, _, _) => [Some(*a), None],
            Instruction::Ori(a, _, _) => [Some(*a), None],
            Instruction::Lui(a, _) => [Some(*a), None],
            Instruction::Ei => [None, None],
            Instruction::Sq(_, _, _) => [None, None],
            Instruction::Lh(a, _, _) => [Some(*a), None],
            Instruction::Lw(a, _, _) => [Some(*a), None],
            Instruction::Lbu(a, _, _) => [Some(*a), None],
            Instruction::Lwr(a, _, _) => [Some(*a), None],
            Instruction::Sb(_, _, _) => [None, None],
            Instruction::Sh(_, _, _) => [None, None],
            Instruction::Sw(_, _, _) => [None, None],
            Instruction::Ld(a, _, _) => [Some(*a), None],
            Instruction::Sd(_, _, _) => [None, None],
        })
        .into_iter()
        .take_while(|x| x.is_some())
        .filter_map(|x| x.and_then(|x| x.non_zero()))
    }

    fn uses(&self) -> impl Iterator<Item = Register> {
        (match self {
            Instruction::Unknown => [None, None],
            Instruction::Sll(_, b, _) => [Some(*b), None],
            Instruction::Srl(_, b, _) => [Some(*b), None],
            Instruction::Sra(_, b, _) => [Some(*b), None],
            Instruction::Sllv(_, b, c) => [Some(*b), Some(*c)],
            Instruction::Srlv(_, b, c) => [Some(*b), Some(*c)],
            Instruction::Srav(_, b, c) => [Some(*b), Some(*c)],
            Instruction::Jr(a) => [Some(*a), None],
            Instruction::Jalr(_, b) => [Some(*b), None],
            Instruction::Movz(_, b, c) => [Some(*b), Some(*c)],
            Instruction::Movn(_, b, c) => [Some(*b), Some(*c)],
            Instruction::Syscall => [None, None],
            Instruction::Break => [None, None],
            Instruction::Sync => [None, None],
            Instruction::Mfhi(_) => [None, None],
            Instruction::Mthi(a) => [Some(*a), None],
            Instruction::Mflo(_) => [None, None],
            Instruction::Mtlo(a) => [Some(*a), None],
            Instruction::Dsllv(_, b, c) => [Some(*b), Some(*c)],
            Instruction::Dsrav(_, b, c) => [Some(*b), Some(*c)],
            Instruction::Dsrlv(_, b, c) => [Some(*b), Some(*c)],
            Instruction::Mult(a, b) => [Some(*a), Some(*b)],
            Instruction::Multu(a, b) => [Some(*a), Some(*b)],
            Instruction::Div(a, b) => [Some(*a), Some(*b)],
            Instruction::Divu(a, b) => [Some(*a), Some(*b)],
            Instruction::Add(_, a, b) => [Some(*a), Some(*b)],
            Instruction::Addu(_, a, b) => [Some(*a), Some(*b)],
            Instruction::Sub(_, a, b) => [Some(*a), Some(*b)],
            Instruction::Subu(_, a, b) => [Some(*a), Some(*b)],
            Instruction::And(_, a, b) => [Some(*a), Some(*b)],
            Instruction::Or(_, a, b) => [Some(*a), Some(*b)],
            Instruction::Xor(_, a, b) => [Some(*a), Some(*b)],
            Instruction::Nor(_, a, b) => [Some(*a), Some(*b)],
            Instruction::Mfsa(_) => [None, None],
            Instruction::Mtsa(a) => [Some(*a), None],
            Instruction::Slt(_, a, b) => [Some(*a), Some(*b)],
            Instruction::Sltu(_, a, b) => [Some(*a), Some(*b)],
            Instruction::Dadd(_, a, b) => [Some(*a), Some(*b)],
            Instruction::Daddu(_, a, b) => [Some(*a), Some(*b)],
            Instruction::Dsub(_, a, b) => [Some(*a), Some(*b)],
            Instruction::Dsubu(_, a, b) => [Some(*a), Some(*b)],
            Instruction::Tge(a, b) => [Some(*a), Some(*b)],
            Instruction::Tgeu(a, b) => [Some(*a), Some(*b)],
            Instruction::Tlt(a, b) => [Some(*a), Some(*b)],
            Instruction::Tltu(a, b) => [Some(*a), Some(*b)],
            Instruction::Teq(a, b) => [Some(*a), Some(*b)],
            Instruction::Tne(a, b) => [Some(*a), Some(*b)],
            Instruction::Dsll(_, b, _) => [Some(*b), None],
            Instruction::Dsrl(_, b, _) => [Some(*b), None],
            Instruction::Dsra(_, b, _) => [Some(*b), None],
            Instruction::Dsll32(_, b, _) => [Some(*b), None],
            Instruction::Dsrl32(_, b, _) => [Some(*b), None],
            Instruction::Dsra32(_, b, _) => [Some(*b), None],
            Instruction::Bgez(a, _) => [Some(*a), None],
            Instruction::J(_) => [None, None],
            Instruction::Jal(_) => [None, None],
            Instruction::Beq(a, b, _) => [Some(*a), Some(*b)],
            Instruction::Bne(a, b, _) => [Some(*a), Some(*b)],
            Instruction::Addiu(a, b, _) => [Some(*a), Some(*b)],
            Instruction::Andi(a, b, _) => [Some(*a), Some(*b)],
            Instruction::Ori(a, b, _) => [Some(*a), Some(*b)],
            Instruction::Lui(_, _) => [None, None],
            Instruction::Ei => [None, None],
            Instruction::Sq(a, b, _) => [Some(*a), Some(*b)],
            Instruction::Lh(_, b, _) => [Some(*b), None],
            Instruction::Lw(_, b, _) => [Some(*b), None],
            Instruction::Lbu(_, b, _) => [Some(*b), None],
            Instruction::Lwr(_, b, _) => [Some(*b), None],
            Instruction::Sb(a, b, _) => [Some(*a), Some(*b)],
            Instruction::Sh(a, b, _) => [Some(*a), Some(*b)],
            Instruction::Sw(a, b, _) => [Some(*a), Some(*b)],
            Instruction::Ld(_, b, _) => [Some(*b), None],
            Instruction::Sd(a, b, _) => [Some(*a), Some(*b)],
        })
        .into_iter()
        .take_while(|x| x.is_some())
        .filter_map(|x| x.and_then(|x| x.non_zero()))
    }

    fn depends_on(&self, register: Register) -> bool {
        self.uses().any(|x| x == register)
    }

    fn depends_on_instruction(&self, other: &Instruction) -> bool {
        other.definitions().any(|x| self.depends_on(x))
    }
}

impl Display for Instruction {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Instruction::Unknown => write!(f, "[unknown]"),
            Instruction::Sll(a, b, c) => write!(f, "sll {a}, {b}, {c}"),
            Instruction::Srl(a, b, c) => write!(f, "srl {a}, {b}, {c}"),
            Instruction::Sra(a, b, c) => write!(f, "sra {a}, {b}, {c}"),
            Instruction::Sllv(a, b, c) => write!(f, "sllv {a}, {b}, {c}"),
            Instruction::Srlv(a, b, c) => write!(f, "srlv {a}, {b}, {c}"),
            Instruction::Srav(a, b, c) => write!(f, "srav {a}, {b}, {c}"),
            Instruction::Jr(a) => write!(f, "jr {a}"),
            Instruction::Jalr(a, b) => write!(f, "jalr {a}, {b}"),
            Instruction::Movz(a, b, c) => write!(f, "movz {a}, {b}, {c}"),
            Instruction::Movn(a, b, c) => write!(f, "movn {a}, {b}, {c}"),
            Instruction::Syscall => write!(f, "syscall"),
            Instruction::Break => write!(f, "break"),
            Instruction::Sync => write!(f, "sync"),
            Instruction::Mfhi(a) => write!(f, "mfhi {a}"),
            Instruction::Mthi(a) => write!(f, "mthi {a}"),
            Instruction::Mflo(a) => write!(f, "mflo {a}"),
            Instruction::Mtlo(a) => write!(f, "mtlo {a}"),
            Instruction::Dsllv(a, b, c) => write!(f, "dsllv {a}, {b}, {c}"),
            Instruction::Dsrav(a, b, c) => write!(f, "dsrav {a}, {b}, {c}"),
            Instruction::Dsrlv(a, b, c) => write!(f, "dsrlv {a}, {b}, {c}"),
            Instruction::Mult(a, b) => write!(f, "mult {a}, {b}"),
            Instruction::Multu(a, b) => write!(f, "multu {a}, {b}"),
            Instruction::Div(a, b) => write!(f, "div {a}, {b}"),
            Instruction::Divu(a, b) => write!(f, "divu {a}, {b}"),
            Instruction::Add(a, b, c) => write!(f, "add {a}, {b}, {c}"),
            Instruction::Addu(a, b, c) => write!(f, "addu {a}, {b}, {c}"),
            Instruction::Sub(a, b, c) => write!(f, "sub {a}, {b}, {c}"),
            Instruction::Subu(a, b, c) => write!(f, "subu {a}, {b}, {c}"),
            Instruction::And(a, b, c) => write!(f, "and {a}, {b}, {c}"),
            Instruction::Or(a, b, c) => write!(f, "or {a}, {b}, {c}"),
            Instruction::Xor(a, b, c) => write!(f, "xor {a}, {b}, {c}"),
            Instruction::Nor(a, b, c) => write!(f, "nor {a}, {b}, {c}"),
            Instruction::Mfsa(a) => write!(f, "mfsa {a}"),
            Instruction::Mtsa(a) => write!(f, "mtsa {a}"),
            Instruction::Slt(a, b, c) => write!(f, "slt {a}, {b}, {c}"),
            Instruction::Sltu(a, b, c) => write!(f, "sltu {a}, {b}, {c}"),
            Instruction::Dadd(a, b, c) => write!(f, "dadd {a}, {b}, {c}"),
            Instruction::Daddu(a, b, c) => write!(f, "daddu {a}, {b}, {c}"),
            Instruction::Dsub(a, b, c) => write!(f, "dsub {a}, {b}, {c}"),
            Instruction::Dsubu(a, b, c) => write!(f, "dsubu {a}, {b}, {c}"),
            Instruction::Tge(a, b) => write!(f, "tge {a}, {b}"),
            Instruction::Tgeu(a, b) => write!(f, "tgeu {a}, {b}"),
            Instruction::Tlt(a, b) => write!(f, "tlt {a}, {b}"),
            Instruction::Tltu(a, b) => write!(f, "tltu {a}, {b}"),
            Instruction::Teq(a, b) => write!(f, "teq {a}, {b}"),
            Instruction::Tne(a, b) => write!(f, "tne {a}, {b}"),
            Instruction::Dsll(a, b, c) => write!(f, "dsll {a}, {b}, {c}"),
            Instruction::Dsrl(a, b, c) => write!(f, "dsrl {a}, {b}, {c}"),
            Instruction::Dsra(a, b, c) => write!(f, "dsra {a}, {b}, {c}"),
            Instruction::Dsll32(a, b, c) => write!(f, "dsll32 {a}, {b}, {c}"),
            Instruction::Dsrl32(a, b, c) => write!(f, "dsrl32 {a}, {b}, {c}"),
            Instruction::Dsra32(a, b, c) => write!(f, "dsra32 {a}, {b}, {c}"),
            Instruction::Bgez(a, b) => write!(f, "bgez {a}, {b:#x}"),
            Instruction::J(a) => write!(f, "j {a:#x}"),
            Instruction::Jal(a) => write!(f, "jal {a:#x}"),
            Instruction::Beq(a, b, c) => write!(f, "beq {a}, {b}, {c:#x}"),
            Instruction::Bne(a, b, c) => write!(f, "bne {a}, {b}, {c:#x}"),
            Instruction::Addiu(a, b, c) => write!(f, "addiu {a}, {b}, {c:#x}"),
            Instruction::Andi(a, b, c) => write!(f, "andi {a}, {b}, {c:#x}"),
            Instruction::Ori(a, b, c) => write!(f, "ori {a}, {b}, {c:#x}"),
            Instruction::Lui(a, b) => write!(f, "lui {a}, {b}"),
            Instruction::Ei => write!(f, "ei"),
            Instruction::Sq(a, b, c) => write!(f, "sq {a}, {c:#x}({b})"),
            Instruction::Lh(a, b, c) => write!(f, "lh {a}, {c:#x}({b})"),
            Instruction::Lw(a, b, c) => write!(f, "lw {a}, {c:#x}({b})"),
            Instruction::Lbu(a, b, c) => write!(f, "lbu {a}, {c:#x}({b})"),
            Instruction::Lwr(a, b, c) => write!(f, "lwr {a}, {c:#x}({b})"),
            Instruction::Sb(a, b, c) => write!(f, "sb {a}, {c:#x}({b})"),
            Instruction::Sh(a, b, c) => write!(f, "sh {a}, {c:#x}({b})"),
            Instruction::Sw(a, b, c) => write!(f, "sw {a}, {c:#x}({b})"),
            Instruction::Ld(a, b, c) => write!(f, "ld {a}, {c:#x}({b})"),
            Instruction::Sd(a, b, c) => write!(f, "sd {a}, {c:#x}({b})"),
        }
    }
}

impl Instruction {
    pub fn is_nop(&self) -> bool {
        match self {
            Instruction::Unknown => true,
            Instruction::Sll(reg1, reg2, 0) => reg1 == reg2,
            Instruction::Addiu(reg1, reg2, 0) => reg1 == reg2,
            Instruction::Ori(reg1, reg2, 0) => reg1 == reg2,
            _ => false,
        }
    }
}
